apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    # - image: us.gcr.io/ticketing-dev-415206/auth
    #   context: auth
    #   sync:
    #     manual:
    #       - src: src/**/*.ts
    #         dest: .
    #   docker:
    #     dockerfile: Dockerfile
    - image: varunkh16/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: varunkh16/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: varunkh16/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-415206
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}